plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

logFilters:
  - text: "eslint-config-react-app@npm:7.0.1 [19d9f] doesn't provide @babel/plugin-syntax-flow (p55d72), requested by eslint-plugin-flowtype"
    level: "discard"
  - text: "eslint-config-react-app@npm:7.0.1 [19d9f] doesn't provide @babel/plugin-transform-react-jsx (p333d7), requested by eslint-plugin-flowtype"
    level: "discard"
  - text: "react-dev-utils@npm:12.0.1 doesn't provide typescript (p59348), requested by fork-ts-checker-webpack-plugin"
    level: "discard"
  - text: "react-dev-utils@npm:12.0.1 doesn't provide webpack (p1012e), requested by fork-ts-checker-webpack-plugin"
    level: "discard"
